"""update ondelete

Revision ID: eb0f4819c8bc
Revises: 7d97c9615407
Create Date: 2026-03-06 07:15:01.054877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0f4819c8bc'
down_revision: Union[str, Sequence[str], None] = '7d97c9615407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lesson_stage'), 'lesson', type_='foreignkey')
    op.create_foreign_key('fk_lesson_stage', 'lesson', 'stage', ['stage_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_task_lesson'), 'task', type_='foreignkey')
    op.create_foreign_key('fk_task_lesson', 'task', 'lesson', ['lesson_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_lesson', 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_lesson'), 'task', 'lesson', ['lesson_id'], ['id'])
    op.drop_constraint('fk_lesson_stage', 'lesson', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lesson_stage'), 'lesson', 'stage', ['stage_id'], ['id'])
    # ### end Alembic commands ###
