"""add premium accounts and settings

Revision ID: 4058ebc3ae14
Revises: c33d3afc2e47
Create Date: 2026-03-12 09:51:41.256253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4058ebc3ae14'
down_revision: Union[str, Sequence[str], None] = 'c33d3afc2e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_premium', sa.Integer(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), server_default='1', nullable=False),
    sa.Column('pay_link', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('is_pay', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('pay_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ofd_url', sa.String(), nullable=True),
    sa.Column('return_url', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_payment_created'), 'payment', ['created'], unique=False)
    op.create_index(op.f('ix_payment_pay_date'), 'payment', ['pay_date'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_uuid'), 'payment', ['uuid'], unique=True)
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium')
    op.drop_index(op.f('ix_payment_uuid'), table_name='payment')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_pay_date'), table_name='payment')
    op.drop_index(op.f('ix_payment_created'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('settings')
    # ### end Alembic commands ###
