"""add user

Revision ID: 56e7596c32eb
Revises: 
Create Date: 2026-02-24 13:25:35.345241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56e7596c32eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('male', 'female', name='gender').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_visited', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_create'), 'user', ['create'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_patronymic'), 'user', ['patronymic'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('verificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationcode_id'), 'verificationcode', ['id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('x_real_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('accept_language', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('detected_os', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_accept_language'), 'device', ['accept_language'], unique=False)
    op.create_index(op.f('ix_device_created'), 'device', ['created'], unique=False)
    op.create_index(op.f('ix_device_detected_os'), 'device', ['detected_os'], unique=False)
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_index(op.f('ix_device_ip_address'), 'device', ['ip_address'], unique=False)
    op.create_index(op.f('ix_device_user_agent'), 'device', ['user_agent'], unique=False)
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_x_real_ip'), 'device', ['x_real_ip'], unique=False)
    op.create_table('firebasetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firebasetoken_created'), 'firebasetoken', ['created'], unique=False)
    op.create_index(op.f('ix_firebasetoken_device_id'), 'firebasetoken', ['device_id'], unique=False)
    op.create_index(op.f('ix_firebasetoken_id'), 'firebasetoken', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firebasetoken_id'), table_name='firebasetoken')
    op.drop_index(op.f('ix_firebasetoken_device_id'), table_name='firebasetoken')
    op.drop_index(op.f('ix_firebasetoken_created'), table_name='firebasetoken')
    op.drop_table('firebasetoken')
    op.drop_index(op.f('ix_device_x_real_ip'), table_name='device')
    op.drop_index(op.f('ix_device_user_id'), table_name='device')
    op.drop_index(op.f('ix_device_user_agent'), table_name='device')
    op.drop_index(op.f('ix_device_ip_address'), table_name='device')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_index(op.f('ix_device_detected_os'), table_name='device')
    op.drop_index(op.f('ix_device_created'), table_name='device')
    op.drop_index(op.f('ix_device_accept_language'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_verificationcode_id'), table_name='verificationcode')
    op.drop_table('verificationcode')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_patronymic'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_create'), table_name='user')
    op.drop_table('user')
    sa.Enum('male', 'female', name='gender').drop(op.get_bind())
    # ### end Alembic commands ###
