"""add stories

Revision ID: a4efdd14ac1f
Revises: afd07defaa60
Create Date: 2026-03-10 07:07:25.118530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4efdd14ac1f'
down_revision: Union[str, Sequence[str], None] = 'afd07defaa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason').create(op.get_bind())
    sa.Enum('LAUGH', 'FIRE', 'ANGRY', name='reaction_type_enum').create(op.get_bind())
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtag_id'), 'hashtag', ['id'], unique=False)
    op.create_index(op.f('ix_hashtag_text'), 'hashtag', ['text'], unique=True)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_short_story', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_id'), 'story', ['id'], unique=False)
    op.create_index(op.f('ix_story_is_short_story'), 'story', ['is_short_story'], unique=False)
    op.create_index(op.f('ix_story_user_id'), 'story', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_created'), 'comment', ['created'], unique=False)
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_index(op.f('ix_comment_story_id'), 'comment', ['story_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('favoritestory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoritestory_created'), 'favoritestory', ['created'], unique=False)
    op.create_index(op.f('ix_favoritestory_id'), 'favoritestory', ['id'], unique=False)
    op.create_index(op.f('ix_favoritestory_story_id'), 'favoritestory', ['story_id'], unique=False)
    op.create_index(op.f('ix_favoritestory_user_id'), 'favoritestory', ['user_id'], unique=False)
    op.create_table('hug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hug_created'), 'hug', ['created'], unique=False)
    op.create_index(op.f('ix_hug_id'), 'hug', ['id'], unique=False)
    op.create_index(op.f('ix_hug_story_id'), 'hug', ['story_id'], unique=False)
    op.create_index(op.f('ix_hug_user_id'), 'hug', ['user_id'], unique=False)
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('type_reaction', postgresql.ENUM('LAUGH', 'FIRE', 'ANGRY', name='reaction_type_enum', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_created'), 'reaction', ['created'], unique=False)
    op.create_index(op.f('ix_reaction_id'), 'reaction', ['id'], unique=False)
    op.create_index(op.f('ix_reaction_story_id'), 'reaction', ['story_id'], unique=False)
    op.create_index(op.f('ix_reaction_user_id'), 'reaction', ['user_id'], unique=False)
    op.create_table('storyattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_link', sa.String(), nullable=False),
    sa.Column('cover_link', sa.String(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyattachment_created'), 'storyattachment', ['created'], unique=False)
    op.create_index(op.f('ix_storyattachment_id'), 'storyattachment', ['id'], unique=False)
    op.create_index(op.f('ix_storyattachment_is_image'), 'storyattachment', ['is_image'], unique=False)
    op.create_index(op.f('ix_storyattachment_story_id'), 'storyattachment', ['story_id'], unique=False)
    op.create_index(op.f('ix_storyattachment_user_id'), 'storyattachment', ['user_id'], unique=False)
    op.create_table('storyhashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyhashtag_hashtag_id'), 'storyhashtag', ['hashtag_id'], unique=False)
    op.create_index(op.f('ix_storyhashtag_id'), 'storyhashtag', ['id'], unique=False)
    op.create_index(op.f('ix_storyhashtag_story_id'), 'storyhashtag', ['story_id'], unique=False)
    op.create_table('storyhiding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyhiding_id'), 'storyhiding', ['id'], unique=False)
    op.create_index(op.f('ix_storyhiding_story_id'), 'storyhiding', ['story_id'], unique=False)
    op.create_index(op.f('ix_storyhiding_user_id'), 'storyhiding', ['user_id'], unique=False)
    op.create_table('storyreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('is_satisfy', sa.Boolean(), nullable=True),
    sa.Column('reason', postgresql.ENUM('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason', create_type=False), nullable=True),
    sa.Column('additional_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyreport_created'), 'storyreport', ['created'], unique=False)
    op.create_index(op.f('ix_storyreport_id'), 'storyreport', ['id'], unique=False)
    op.create_index(op.f('ix_storyreport_is_satisfy'), 'storyreport', ['is_satisfy'], unique=False)
    op.create_index(op.f('ix_storyreport_object_id'), 'storyreport', ['object_id'], unique=False)
    op.create_index(op.f('ix_storyreport_reason'), 'storyreport', ['reason'], unique=False)
    op.create_index(op.f('ix_storyreport_subject_id'), 'storyreport', ['subject_id'], unique=False)
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_created'), 'view', ['created'], unique=False)
    op.create_index(op.f('ix_view_id'), 'view', ['id'], unique=False)
    op.create_index(op.f('ix_view_story_id'), 'view', ['story_id'], unique=False)
    op.create_index(op.f('ix_view_user_id'), 'view', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_user_id'), table_name='view')
    op.drop_index(op.f('ix_view_story_id'), table_name='view')
    op.drop_index(op.f('ix_view_id'), table_name='view')
    op.drop_index(op.f('ix_view_created'), table_name='view')
    op.drop_table('view')
    op.drop_index(op.f('ix_storyreport_subject_id'), table_name='storyreport')
    op.drop_index(op.f('ix_storyreport_reason'), table_name='storyreport')
    op.drop_index(op.f('ix_storyreport_object_id'), table_name='storyreport')
    op.drop_index(op.f('ix_storyreport_is_satisfy'), table_name='storyreport')
    op.drop_index(op.f('ix_storyreport_id'), table_name='storyreport')
    op.drop_index(op.f('ix_storyreport_created'), table_name='storyreport')
    op.drop_table('storyreport')
    op.drop_index(op.f('ix_storyhiding_user_id'), table_name='storyhiding')
    op.drop_index(op.f('ix_storyhiding_story_id'), table_name='storyhiding')
    op.drop_index(op.f('ix_storyhiding_id'), table_name='storyhiding')
    op.drop_table('storyhiding')
    op.drop_index(op.f('ix_storyhashtag_story_id'), table_name='storyhashtag')
    op.drop_index(op.f('ix_storyhashtag_id'), table_name='storyhashtag')
    op.drop_index(op.f('ix_storyhashtag_hashtag_id'), table_name='storyhashtag')
    op.drop_table('storyhashtag')
    op.drop_index(op.f('ix_storyattachment_user_id'), table_name='storyattachment')
    op.drop_index(op.f('ix_storyattachment_story_id'), table_name='storyattachment')
    op.drop_index(op.f('ix_storyattachment_is_image'), table_name='storyattachment')
    op.drop_index(op.f('ix_storyattachment_id'), table_name='storyattachment')
    op.drop_index(op.f('ix_storyattachment_created'), table_name='storyattachment')
    op.drop_table('storyattachment')
    op.drop_index(op.f('ix_reaction_user_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_story_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_created'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_index(op.f('ix_hug_user_id'), table_name='hug')
    op.drop_index(op.f('ix_hug_story_id'), table_name='hug')
    op.drop_index(op.f('ix_hug_id'), table_name='hug')
    op.drop_index(op.f('ix_hug_created'), table_name='hug')
    op.drop_table('hug')
    op.drop_index(op.f('ix_favoritestory_user_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_story_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_created'), table_name='favoritestory')
    op.drop_table('favoritestory')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_story_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_created'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_story_user_id'), table_name='story')
    op.drop_index(op.f('ix_story_is_short_story'), table_name='story')
    op.drop_index(op.f('ix_story_id'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_hashtag_text'), table_name='hashtag')
    op.drop_index(op.f('ix_hashtag_id'), table_name='hashtag')
    op.drop_table('hashtag')
    sa.Enum('LAUGH', 'FIRE', 'ANGRY', name='reaction_type_enum').drop(op.get_bind())
    sa.Enum('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason').drop(op.get_bind())
    # ### end Alembic commands ###
