"""update foreign keys

Revision ID: 7d97c9615407
Revises: df98465bab62
Create Date: 2026-03-05 11:46:26.516297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d97c9615407'
down_revision: Union[str, Sequence[str], None] = 'df98465bab62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_lesson_stage', 'lesson', 'stage', ['stage_id'], ['id'])
    op.create_foreign_key('fk_task_lesson', 'task', 'lesson', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lesson_stage', 'task', type_='foreignkey')
    op.drop_constraint('fk_task_lesson', 'lesson', type_='foreignkey')
    # ### end Alembic commands ###
