"""update nullable id

Revision ID: afd07defaa60
Revises: eb0f4819c8bc
Create Date: 2026-03-06 07:17:26.439486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd07defaa60'
down_revision: Union[str, Sequence[str], None] = 'eb0f4819c8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lesson', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
