"""update stories

Revision ID: c33d3afc2e47
Revises: a4efdd14ac1f
Create Date: 2026-03-11 08:05:43.798655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33d3afc2e47'
down_revision: Union[str, Sequence[str], None] = 'a4efdd14ac1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_created'), 'subscription', ['created'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_object_id'), 'subscription', ['object_id'], unique=False)
    op.create_index(op.f('ix_subscription_subject_id'), 'subscription', ['subject_id'], unique=False)
    op.create_table('userblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userblock_created'), 'userblock', ['created'], unique=False)
    op.create_index(op.f('ix_userblock_id'), 'userblock', ['id'], unique=False)
    op.create_index(op.f('ix_userblock_object_id'), 'userblock', ['object_id'], unique=False)
    op.create_index(op.f('ix_userblock_subject_id'), 'userblock', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userblock_subject_id'), table_name='userblock')
    op.drop_index(op.f('ix_userblock_object_id'), table_name='userblock')
    op.drop_index(op.f('ix_userblock_id'), table_name='userblock')
    op.drop_index(op.f('ix_userblock_created'), table_name='userblock')
    op.drop_table('userblock')
    op.drop_index(op.f('ix_subscription_subject_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_object_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_created'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
